### PR TITLE
feat: lang select

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This is a draft feature. I didn't make tests for it yet. 
Autocomplete prompt to select HTML lang attribute from this [country list](https://gist.githubusercontent.com/jrnk/8eb57b065ea0b098d571/raw/97efa7bc28c72bacfebce73e28e35cdfea34db63/ISO-639-1-language.json)
Prompt looks like this:
```
? Select language »
>   English
    Abkhaz
    Afar
    Afrikaans
    Akan
    Albanian
    Amharic
    Arabic
    Aragonese
  ↓ Armenian
```

What do you think?

P.S
[Video](https://skr.sh/v2YK0VQCW5h).

### CODE REVIEW

**Comment by coliff** [comment]
interesting idea, though usually when setting a language on a webpage I also set the locale.. e.g. `en-gb` for a UK site or `en-us` if its for US etc.
https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes
So I wonder if it should also include these options too. I think it needs to be quick and easy to select an option from the list.

**Comment by vltansky** [comment]
You probably right. Language code will be more xlearhoice.

**Comment by vltansky** [comment]
Closed it by mistake... I'll make a few changes and open a new one.

**Comment by vltansky** [comment]
> interesting idea, though usually when setting a language on a webpage I also set the locale.. e.g. `en-gb` for a UK site or `en-us` if its for US etc.
> https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes
> So I wonder if it should also include these options too. I think it needs to be quick and easy to select an option from the list.

I took a list of language codes (in en-us, en-gb format) from [here](https://datahub.io/core/language-codes/r/3.html).
That how it looks now:
```
? Select language »
>   af
    af-NA
    af-ZA
    agq
    agq-CM
    ak
    ak-GH
    am
    am-ET
  ↓ ar
```
[Video](https://skr.sh/v2ZueyRq9RQ)

**Comment by coliff** [comment]
I think many of these are not valid, the country code needs to be 2 characters.. and I think many of the ones on that list are not needed (for example en-DE)... think we should look for a better source

**Comment by vltansky** [comment]
Can you help me to find a good source?

**Comment by coliff** [comment]
> Can you help me to find a good source?

sure, I'm looking now...  :-)

**Comment by roblarsen** [comment]
I had never researched what these actually are. They appear to be ISO 639-1 codes. Here's a list in CSV format. 

alpha2,English
aa,Afar
ab,Abkhazian
ae,Avestan
af,Afrikaans
ak,Akan
am,Amharic
an,Aragonese
ar,Arabic
as,Assamese
av,Avaric
ay,Aymara
az,Azerbaijani
ba,Bashkir
be,Belarusian
bg,Bulgarian
bh,Bihari languages
bi,Bislama
bm,Bambara
bn,Bengali
bo,Tibetan
br,Breton
bs,Bosnian
ca,Catalan; Valencian
ce,Chechen
ch,Chamorro
co,Corsican
cr,Cree
cs,Czech
cu,Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic
cv,Chuvash
cy,Welsh
da,Danish
de,German
dv,Divehi; Dhivehi; Maldivian
dz,Dzongkha
ee,Ewe
el,"Greek, Modern (1453-)"
en,English
eo,Esperanto
es,Spanish; Castilian
et,Estonian
eu,Basque
fa,Persian
ff,Fulah
fi,Finnish
fj,Fijian
fo,Faroese
fr,French
fy,Western Frisian
ga,Irish
gd,Gaelic; Scottish Gaelic
gl,Galician
gn,Guarani
gu,Gujarati
gv,Manx
ha,Hausa
he,Hebrew
hi,Hindi
ho,Hiri Motu
hr,Croatian
ht,Haitian; Haitian Creole
hu,Hungarian
hy,Armenian
hz,Herero
ia,Interlingua (International Auxiliary Language Association)
id,Indonesian
ie,Interlingue; Occidental
ig,Igbo
ii,Sichuan Yi; Nuosu
ik,Inupiaq
io,Ido
is,Icelandic
it,Italian
iu,Inuktitut
ja,Japanese
jv,Javanese
ka,Georgian
kg,Kongo
ki,Kikuyu; Gikuyu
kj,Kuanyama; Kwanyama
kk,Kazakh
kl,Kalaallisut; Greenlandic
km,Central Khmer
kn,Kannada
ko,Korean
kr,Kanuri
ks,Kashmiri
ku,Kurdish
kv,Komi
kw,Cornish
ky,Kirghiz; Kyrgyz
la,Latin
lb,Luxembourgish; Letzeburgesch
lg,Ganda
li,Limburgan; Limburger; Limburgish
ln,Lingala
lo,Lao
lt,Lithuanian
lu,Luba-Katanga
lv,Latvian
mg,Malagasy
mh,Marshallese
mi,Maori
mk,Macedonian
ml,Malayalam
mn,Mongolian
mr,Marathi
ms,Malay
mt,Maltese
my,Burmese
na,Nauru
nb,"Bokmål, Norwegian; Norwegian Bokmål"
nd,"Ndebele, North; North Ndebele"
ne,Nepali
ng,Ndonga
nl,Dutch; Flemish
nn,"Norwegian Nynorsk; Nynorsk, Norwegian"
no,Norwegian
nr,"Ndebele, South; South Ndebele"
nv,Navajo; Navaho
ny,Chichewa; Chewa; Nyanja
oc,Occitan (post 1500)
oj,Ojibwa
om,Oromo
or,Oriya
os,Ossetian; Ossetic
pa,Panjabi; Punjabi
pi,Pali
pl,Polish
ps,Pushto; Pashto
pt,Portuguese
qu,Quechua
rm,Romansh
rn,Rundi
ro,Romanian; Moldavian; Moldovan
ru,Russian
rw,Kinyarwanda
sa,Sanskrit
sc,Sardinian
sd,Sindhi
se,Northern Sami
sg,Sango
si,Sinhala; Sinhalese
sk,Slovak
sl,Slovenian
sm,Samoan
sn,Shona
so,Somali
sq,Albanian
sr,Serbian
ss,Swati
st,"Sotho, Southern"
su,Sundanese
sv,Swedish
sw,Swahili
ta,Tamil
te,Telugu
tg,Tajik
th,Thai
ti,Tigrinya
tk,Turkmen
tl,Tagalog
tn,Tswana
to,Tonga (Tonga Islands)
tr,Turkish
ts,Tsonga
tt,Tatar
tw,Twi
ty,Tahitian
ug,Uighur; Uyghur
uk,Ukrainian
ur,Urdu
uz,Uzbek
ve,Venda
vi,Vietnamese
vo,Volapük
wa,Walloon
wo,Wolof
xh,Xhosa
yi,Yiddish
yo,Yoruba
za,Zhuang; Chuang
zh,Chinese
zu,Zulu

**Comment by vltansky** [comment]
But this list not contains en-us, en-gb and etc. as @coliff proposed. It looks like a first list I used.

**Comment by roblarsen** [comment]
> The lang attribute (in no namespace) specifies the primary language for the element’s contents and for any of the element’s attributes that contain text. Its value must be a valid BCP 47 language tag, or the empty string. Setting the attribute to the empty string indicates that the primary language is unknown. [BCP47]

Here's the BCP 47 spec

https://tools.ietf.org/html/bcp47

I think we can safely use a subset. Can we let people who know better enter their own?

**Comment by vltansky** [comment]
Sorry, I didn't understand your message.
By subset do you mean ISO 639-1?

**Comment by vltansky** [comment]
We can add "custom" option to autoselect and put it second after "en". After choosing "custom" user will get another prompt where he can enter custom value (without validation - ?)

**Comment by roblarsen** [comment]
> Sorry, I didn't understand your message.
> By subset do you mean ISO 639-1?

Yes, especially if we can let people type in something.

**Comment by vltansky** [comment]
@roblarsen another ISO 639-1 autocomplete with "custom" option. What do you way?
@coliff I'd be happy if you could take a look too.
1.
```
$ node index.js ./out/vlad
? Select language »
>   English
    Enter custom
    Abkhaz
    Afar
    Afrikaans
    Akan
    Albanian
    Amharic
    Arabic
  ↓ Aragonese
```

2.
```
√ Select language » Enter custom
? Enter custom language code »
```
3.
```
$ node index.js ./out/vlad
√ Select language » Enter custom
√ Enter custom language code ... en-US
```
$ node index.js ./out/vlad
√ Select language » Enter custom
√ Enter custom language code ... en-US
√ html5-boilerplate@latest copied to D:\projects\create-html5-boilerplate\out\vlad in 1.62 seconds . Have fun!
```

**Comment by vltansky** [comment]
@coliff looks good?

```
? Select language » de
>   German (de)
    Greek, Modern (el)
    Hebrew (modern) (he)
    North Ndebele (nd)
    South Ndebele (nr)
    Divehi; Dhivehi; Maldivian; (dv)
    Indonesian (id)
    Sundanese (su)
    Tibetan Standard, Tibetan, Central (bo)
  ↓ Venda (ve)
```

@roblarsen you can git clone this branch and run `npm link`, then npm will use it as a global node module.
I'll write some tests for this today/tomorrow and then it will be ready for merge.

**Comment by coliff** [comment]
@vltansky great work! I just tested your latest update and it looks great. I can now type `de` to get German and having the language code in brackets after the name is helpful. 👍

**Comment by vltansky** [comment]
Ok, it's done and ready for merge as for me.
But there is a few extra I'd want to share:
1. I've added the argument `--yes` (alias `-y`) as you have in `npm init -y` to skip prompts and go with the default choices. (default lang is `lang=""` - empty)
2. Argument `--lang=` (without alias) to pass lang value as an argument and to skip prompt. Example `npm init html5-boilerplate --lang=en-US`. 
3. I do not know how to test prompts. That one of the reasons why I added `--lang`, I wrote tests for the lang functionality, but not for the prompt. I marked prompt code sections with `istanbul ignore`.

**Comment by vltansky** [comment]
Done :)

**Comment by vltansky** [comment]
@roblarsen can we merge this?

**Comment by roblarsen** [comment]
done!

**Pull request merged**
