### PR TITLE
chore: semantic release

### LINKED ISSUE #26: Use semantic-release
Look very good as for me, what do you think?
https://github.com/semantic-release/semantic-release

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

closes #26 
https://github.com/semantic-release/semantic-release

### CODE REVIEW

**Comment by vltansky** [comment]
@roblarsen I implemented it to my repo, you can take a look on it here: https://github.com/vltansky/elapsed-time-logger

**Comment by roblarsen** [comment]
@vltansky can you fix the package-lock again? I'll merge this and we can think about a new release that will use this

**Comment by vltansky** [comment]
@roblarsen done.
Don't forget to add `npm_token` and `GITHUB_TOKEN` to secrets keys.
Also, we need to create `next` branch. Commits there will release `@next` version for pre-releases

**Comment by roblarsen** [comment]
We have an existing NPM_TOKEN.  Isn't the GITHUB_TOKEN automatic?

**Comment by vltansky** [comment]
Don't know. Maybe. We can test it on next branch.

**Comment by roblarsen** [comment]
👍

**Review by roblarsen — APPROVED** [review]

**Pull request merged**
