### PR TITLE
feat: eslint

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This PR adds eslint configs (extends `eslint:recommended, airbnb/base, plugin:prettier/recommended`) - run `npm run lint`, lint workflow for PRs and VScode settings that enables eslint and prettier for the project by default

### CODE REVIEW

**Comment by Jeroen-Matthijssens** [comment]
I was wondering how everyone else feels about a couple of things.

There is a file added here `.vscode/settings.json`. This is a configuration file for a specific editor. If I use a different editor that file is pretty much useless to me, but perhaps I am willing to add specific configuration for my editor of choice. However this may lead to an arbitrary large collection of configuration for random editors that happend to have been used on the project at some point in history. To me that does not feel very nice. On the flip side if you leave out, you may miss useful configuration or need some other mechanism for distributing it.

So I was wondering how other people approach this.

A second thing I noticed is that there appears to be a merge commit from master into this branch. Personally I would have rebased this branch on top of master, perhaps squashing some commits. But there may be reasons I am missing which would make that a bad idea.

**Comment by coliff** [comment]
Adding eslint workflow for this project is a great idea. 👍   I'm not in favour of adding a `.vscode/` directory though. VS Code is awesome, it's my code editor of choice and is the most popular editor, but I think this project should be platform/editor-agnostic and would suggest to not commit the VS Code settings.

**Comment by vltansky** [comment]
.vscode settings giving a power of eslint and prettier on-save instead of only pre commit. I think this is awesome functionality in a price of one json file.. I see a lot of projects leveraging this

**Comment by coliff** [comment]
ok, fair points. :-)  If we do add `.vscode/settings.json` then I think it'd make sense to add an `.vscode/extensions.json` file with this so it recommends the extensions. I use a similar thing with projects I work on:

```json
{
  "recommendations": [
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode"
  ]
}
```

**Comment by vltansky** [comment]
> ok, fair points. :-) If we do add `.vscode/settings.json` then I think it'd make sense to add an `.vscode/extensions.json` file with this so it recommends the extensions. I use a similar thing with projects I work on:
> 
> ```json
> {
>   "recommendations": [
>     "EditorConfig.EditorConfig",
>     "esbenp.prettier-vscode"
>   ]
> }
> ```

Done

**Comment by roblarsen** [comment]
@Jeroen-Matthijssens I will squash and merge this PR into master, so the commit into the main branch will be clean.

I'm +1 on the VS Code stuff. It's relatively unobtrusive and I wouldn't propose adding anything for any other editors since I too use it exclusively. 

We can always change our minds.

@vltansky can you fix the conflicts? I'll merge.

**Review by roblarsen — APPROVED** [review]

**Comment by vltansky** [comment]
@roblarsen fixed

**Comment by roblarsen** [comment]
Thanks!

**Comment by roblarsen** [comment]
I forgot semantic-release

**Comment by vltansky** [comment]
v0.3 release as this PR contained `feat:` prefix in one of the commits
https://github.com/semantic-release/semantic-release#commit-message-format
Although nice to see that semantic-release works and how it works, this kind of PR shouldn't trigger release (as it doesn't have any feature, only development tools). So need to be careful with prefixes (telling this to myself)

**Comment by roblarsen** [comment]
Yeah, it's so cool to see it work. I just forgot about it when I bundled up your commit messages. We can manage it better in the future. No worries at all.

**Pull request merged**
