### PR TITLE
Update changelog for 0.2.0

### PR DESCRIPTION
**Pull request by roblarsen**

### CODE REVIEW

**Review by vltansky — APPROVED** [review]

**Comment by vltansky** [comment]
Need to bump version in package.json

**Comment by vltansky** [comment]
Need to bump version in package.json

**Comment by vltansky** [comment]
bump version PR: #54

**Comment by coliff** [comment]
looks good. 👍  I just made a few minor changes to capitalize first word from each item and removed an unnecessary comma after the month name.

**Review by coliff — APPROVED** [review]

**Pull request merged**
