### PR TITLE
ESM + Tests + Making Everything Green

### PR DESCRIPTION
**Pull request by roblarsen**
General cleanup, building on the work Vlad did to start the new version. I want to get this to a nice state and then add a couple of features. 

I'll update as I go, here in the issue.

### CODE REVIEW

**Comment by roblarsen** [comment]
```
Test Suites: 1 failed, 1 total
Tests:       102 failed, 1 passed, 103 total
Snapshots:   0 total
Time:        5.053 s
```

🍾

**Comment by roblarsen** [comment]
Epic holiday weekend. Not everything even makes sense, but we need to get some features in here before we release the main project.

**Comment by roblarsen** [comment]
todo: npm ci just doesn't work with the Eslint action. It may work with coverage.yaml, but I'm too afraid to try. 

The sematic release action is an issue, but I want to pull that out of the project anyway.

**Review by coliff — APPROVED** [review]
all tests passing now. NICE!

**Comment by vltansky** [comment]
Great work @roblarsen !

**Pull request merged**
