### PR TITLE
CI: Prettier workflow

### PR DESCRIPTION
**Pull request by vltansky**
Was playing with GitHub actions and get with the idea to run prettier on push/pull request instead of pre-commit.
Pre-commit can take time and sometimes break the commit process. When you're committing 1k files it can take even few minutes. This is not really solve something in this project. But it's cool :)
image
image

### CODE REVIEW

**Comment by vltansky** [comment]
Workflow is failing cause of package.json script. It will be fine when merged.

**Comment by vltansky** [comment]
Can you take a look on this?) @collif @roblarsen

**Comment by roblarsen** [comment]
This looks good to me. We just need to clean up the conflicts

**Comment by coliff** [comment]
Prettier is great and I definitely approve of formatting our JS/CSS and markdown etc with it. 👍  I haven't tested this PR, but it looks good at a glance. I do think that we need to add some notes about this in the README and Contributing guide if we proceed though. Otherwise contributors might find it confusing seeing their formatting change unexpectedly.

**Comment by coliff** [comment]
Maybe in the Pull Request template checklist:
[ ] My code follows the code style of this project
could be:
[ ] My code follows the code style of this project (formatted with [Prettier](https://prettier.io/))

or perhaps as an additional checkmark instead:
[ ] My code is formatted with [Prettier](https://prettier.io/) 

We could also consider adding a Code Style: Prettier badge to the top of the README
[code style: prettier](https://github.com/prettier/prettier)

**Pull request closed without merging**
