### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by vltansky**
adds `npm run format` that uses prettier to format code

### CODE REVIEW

**Comment by coliff** [comment]
I'm personally a big fan of Prettier and use it on all my personal and work projects and think it'd be good to add here. What is the reasoning behind the rules in the `.prettierrc` config though - can't we just go with the Prettier defaults?

**Comment by vltansky** [comment]
I personally prefer a width of 120 (default is 80) and useTabs: true (default: false).
But if you prefer default options, let's go for default.

**Comment by roblarsen** [comment]
I would prefer the prettier defaults since then we don't have to have a conversation about it

**Comment by vltansky** [comment]
Done

**Comment by coliff** [comment]
Related note: I think Prettier is great for markdown, CSS and JS - but it's horrible for HTML. [See here for what it does to our boilerplate index page.](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlXOuLCoEMBnTgXjpCgQAtACtO-YhygBzPiH70oDJnHaZFxYqgpwY7VqXYAnTrrkBXGADMhADgUNNqGAEsYVODVQB6V+8+OWjp6xFDsOnKYcJxgRi4ErtASkLAIMHIOUE7B+mER-ABuLnAA7gQQRjDJ0PCwciUumDCkPFFFYHBCDU2kADTELlBuLuxUQjGjcDwAjJmagdq6+gRGEESVeHIQ0kh+HtWpdfwS3hpBS8Qra3AbWzv4RAe16ccgxKcLOZer6-h3SOYjFQnmkMm8PllziErr9NvxtkgXBR2NI4CCjvJwYoFlRBgBrYhGOBUOTIoZWaJVN6kIlWOScNxwAB0JTgACMyS4KZwqWdULioASiST+OwCAQPEIYBBzGBSEIXCkJDS4HT+IroEyCDI5lp0EIhMQAAocDrEKzsdqajUDLLNEirCAwYiYFxE3AVPDEA3YyH8-GE4n0-AeTikOC6ZW0uRgbjeQRGZG4gBezNj4hAfIFQqD-B5eFD4cj1Oj-HT3mRgyZ6cynwueSm-HtOiEkCoFXRLxAAGILX32JkfOG1L7UGyIJg8L6nPrDQBBTCYYh4GVGYgM+DECrEMUSxXsRJZFLPMg3Eg+hYEGgACWJ7eIJQqVEw6GIABVSC5OANv9e3wBZAAZABWYgACEIBcDwjAlA9mR8K8FhiOIEnXIwwDkMRvAKBBsCMCsJxuIZkyMIQAGYmWmaZKKZCgqzEBQfGQ+IYD5ZjUM4dDMM4bwJXMaRBk4JkGMzJjYhYtjxI4rj+CwysoGEjMvG8djWIYBZZ2IABxCBtg8Yg5zCKg8FcWMkAMdgZBIABVOchAADUcxyhAATWIaViDZEgV0BddGQAcm-ABJAARJlvSESSULUyFNAaKBsBKJlpH0HhzXMKBcBcaBiAACgASmIYBiBSpkAEctXMMNcuMaRzB0WBOEKgBfABuEr2HK4g0oAbQAXXa0qqG64gAGooFKYgQrg1rAk0FLcv82JVHgfz+n82yHKc+zXLW4h-PYSwIH8-LBvYRbTBgPaDsEKA8Do1MgoIPaYCMcw4FOjqLt0Nb-NeyzOHKSpfq89gUhOs7voS66CBROAilKE6FhUqSYqcVS0Iw-hyBgAhOCQbxvBKYnkt06RJUs0YTMVITIAobxKeM0yhJEndODwTLlNUxQfHHSdR28ZhaBAXoQDWQ9OGQUBjFWEojWMBBJZQUYSnYPBJdFtkjDBvFdAAZVhsBBmkZBXve0WhYAdU-eBAbBuA9cV4YinwZBwG4EWQEEm4YCNbXpGRZALSoUxRbEAAPMDtbAXWYD18I4EAwY4CD0ZQ5ACO9eNjwAEVzCdFOkGD9PYZMG43aFz2VkGGBLcaZpkFsAAGUWrlMS3tYIN2VmiG4cM9sr8-gP21iVkAuCECa4CiTBPaJQe3TgP2UUDou07gUXTDo023o3kAGRkXOh8L4u970Nk656ZAACZRf+qDjYAYQgChV5AaJgM9qq4Dfdg2SV0+osCjvSCglNIetUaGUwHrEMJ917NWakAA)

it capitalizes the doctype at the top (which is less efficient when gzipped), it adds unnecessary XHTML style closing tags to the meta tags in the head (yuk!). It also does some other weird stuff with closing tags. I'm just mentioning this since we could consider adding Prettier to other repos like main.css, but I suggest keeping it away from any HTML. :-)

**Pull request merged**
