### PR TITLE
tests

### PR DESCRIPTION
**Pull request by vltansky**
#4 

- [x] temp folder deleted after copy
- [x] target folder is created
- [x] target folder contains files
- [x] target folder contain specific files  (index.html, css, package.json etc.)
- [x] version downloading feature works
- [x] version downloading works both with 'v' and without (-r=7.2.0 | v7.2.0 | 7.2)
- [x] version alias works
- [x] wrong version outputs error

- [x] create coverage using Istanbul (included in jest)
- [x]  upload to converage.io via github actions

### CODE REVIEW

**Comment by roblarsen** [comment]
@vltansky I saw your request for the WIP app- I think I'd like to just experiment with the "drafts" feature for now. It seems to serve the same purpose. I like WIP, so if we feel like drafts isn't doing it for us we can install it at a later date.

**Comment by vltansky** [comment]
Ok, actually draft function looks good. I'm fine with it, just didn't use it till now.

**Comment by vltansky** [comment]
I've finished with most of tests. I do have some problems with coverage generation. Do we need it?
image

**Comment by vltansky** [comment]
I handled coverage problem, you can try it by running `npm run coverage'. I need your help to upload it to coverage.io via GitHub actions.

Beside of this I think this is ready to be reviewed.

**Comment by vltansky** [comment]
@roblarsen we can use https://github.com/marketplace/actions/coveralls-github-action (coveralls) or https://github.com/codecov/codecov-action (codecov)

**Comment by roblarsen** [comment]
@vltansky What help do you need? I'll get to the review of this over the weekend.

**Comment by vltansky** [comment]
Just I think I don't have a permissions to setup GitHub actions or do I? From the nodejs side everything is ready..

**Comment by roblarsen** [comment]
Check if you can add a new workflow now

**Comment by vltansky** [comment]
Done.

**Comment by roblarsen** [comment]
This is a great starting point for this feature. There's more to do, but this is enough to ship. I'll set up the npm publish stuff and we can fill out the readme and then we can get this (and the 8.0 release) out the door.

**Pull request merged**
