### PR TITLE
feat: check if folder is empty

### PR DESCRIPTION
**Pull request by vltansky**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Check if folder is empty

```
√ D:\projects\create-html5-boilerplate\out\null is not empty folder, proceed? ... yes
√ Select language » English (en)
√ html5-boilerplate@latest copied to D:\projects\create-html5-boilerplate\out\null in 3.09 seconds . Have fun!
```

```
√ D:\projects\create-html5-boilerplate\out\null is not empty folder, proceed? ... no
Aborted
```

This branch is based on `lang` branch as it has a lot of changes including `prompts` module.

### CODE REVIEW

**Comment by roblarsen** [comment]
Nice. We'll work on getting this in once the lang branch is merged.

**Comment by vltansky** [comment]
@roblarsen @coliff Should `-y` (skip argument) skip this question?

**Comment by vltansky** [comment]
This one is ready too. Although I still have a problem with testing.. I'd be happy with help. Need to mock prompt node module somehow..

**Comment by roblarsen** [comment]
@vltansky do you want to open an issue that describes the question you have about testing? We can focus on fixing that and do "help wanted" if we need to.  I'll work on merging this in.

**Comment by vltansky** [comment]
https://github.com/h5bp/create-html5-boilerplate/issues/50

Do you want to merge this? And leave tests subject for separate future PR (as it not directly blocking this PR, but overall issue)?

**Comment by roblarsen** [comment]
👍

**Pull request merged**
